spring.datasource.url=jdbc:postgresql://localhost:5432/doc_ai_db
spring.datasource.username=postgres
# This MUST be the exact password you typed into the VS Code Database Client!
spring.datasource.password=SHAsha123@

# Stop massive files before they even reach your Java code
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

# Hibernate properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# File Upload Limits
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Groq API Configuration
groq.api.url=${API_URL}
groq.api.key=${AI_API_KEY}